### PR TITLE
Handle kanji data 'meanings' that contain curly braces.

### LINKED ISSUE #191: Three kanji fail to parse when running update-db.js
The last kanji dictionary has three lines that fail to parse.
I'm not sure why but I'd guess the regex doesn't handle them for some reason.

```
Parsing KANJD213 dictionary from 2020-07-25
Failed to parse line: 𡱖 X2830 U21C56 B44 S9 つび くぼ {female genitalia} {vulva} {{kokuji}} 
Failed to parse line: 𨫤 .=.=== U28AE4 B167 S19 ひ {metal flow} {{kokuji}} 
Failed to parse line: 𪃹 .=.=== U2A0F9 B196 S20 じない {thrush} {{kokuji}} 
```

### PR DESCRIPTION
**Pull request by melink14**
Previously, the regex only matched meanings that did not contain
a close brace which excluded the {{kokuji}} marker added for 3 kanji.

This change removes that restriction matching anything between open
and close braces.

Updates kanji.dat with 3 new kanji!

Fixes #191.

### CODE REVIEW

File: utils/update-db.js [hunk 1]
```diff
@@ -276,8 +276,10 @@ class KanjiDictParser extends Writable {
     //   𡗗 X253E U215D7 B37 S5 Ypeng3
     //   𢦏 .=.=== U2298F B62 S6 Yzai1 {to cut} {wound} {hurt}
     //   𢈘 .=.=== U22218 B53 S9 N1510 DP3845 ロク しか か
+    //   𪃹 .=.=== U2A0F9 B196 S20 じない {thrush} {{kokuji}}
     //
     // (Yes, including the trailing spaces too.)
+    // (The kokuji are usually rendered as {(kokuji)} though Jim says he added them as {{kokuji}} to the readings which doesn't seem true anymore)
```
Comment (Stephie) [inline utils/update-db.js:282]: Rephrase comment to be more concise

Comment (melink14) [reply utils/update-db.js]: Not sure if it's more concise but I moved the comment closer to the example and made it more explicit.
Thanks!
